[project]
name = 'Tokenized-Autonomous-Outdoor-Pest-Control-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.effectiveness-monitoring]
path = 'contracts/effectiveness-monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.prevention-planning]
path = 'contracts/prevention-planning.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
